# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ANSWERS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"QUESTION_ID" INTEGER NOT NULL,"CHOICE_ID" INTEGER NOT NULL,"USER_ID" INTEGER NOT NULL);
create table "Choices" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"TEXT" VARCHAR NOT NULL,"QUESTION_ID" INTEGER,"NEXT_QUESTION_ID" INTEGER,"RESULT_ID" INTEGER);
create table "QUESTIONS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"TEXT" VARCHAR NOT NULL);
create table "RESULTS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"TEXT" VARCHAR NOT NULL);
create table "USERS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"USERNAME" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL);
alter table "ANSWERS" add constraint "ANS_CHOICE_FK" foreign key("CHOICE_ID") references "Choices"("id") on update NO ACTION on delete NO ACTION;
alter table "ANSWERS" add constraint "ANS_QUEST_FK" foreign key("QUESTION_ID") references "QUESTIONS"("id") on update NO ACTION on delete NO ACTION;
alter table "Choices" add constraint "Quest_FK" foreign key("QUESTION_ID") references "QUESTIONS"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "ANSWERS" drop constraint "ANS_CHOICE_FK";
alter table "ANSWERS" drop constraint "ANS_QUEST_FK";
alter table "Choices" drop constraint "Quest_FK";
drop table "ANSWERS";
drop table "Choices";
drop table "QUESTIONS";
drop table "RESULTS";
drop table "USERS";

